### ISSUE TITLE
Unable to remove finally tasks in pipeline builder mode

### ISSUE THREAD

**Issue by RoboMWM** [openshift-pipelines/console-plugin#181]
# Expected Behavior

Finally task gets removed from pipeline when removing the finally tasks and saving the pipeline in the "pipeline builder" mode.

# Actual Behavior

The finally tasks do not get removed and remain in the pipeline.

# Steps to Reproduce the Problem

1. Create a finally task in a pipeline in pipeline builder
2. Save pipeline
3. Edit pipeline and remove finally task in pipeline builder
4. Save pipeline
5. Observe that the finally task has not been removed

# Additional Info

- OpenShift version: 4.16.7 (also present in 4.12)
- Red Hat OpenShift Pipelines Operator 1.16.0

**Comment by lokanandaprabhu** [comment]
Thanks for reporting this. Created PR - https://github.com/openshift-pipelines/console-plugin/pull/183 to handle the issue.
